SDO-513: Add security recommendations on manual install
akeneo/pim-docs pull request #1858
Opened 2023-06-01 10:31 UTC by mota-lhd

**Description**

docs: add security recommendations page

**Definition Of Done**

| Q                                 | A
| --------------------------------- | ---
| Technical Review and 2 GTM        | Todo
| English Review and 1 GTM          | Todo

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2023-06-01 13:11 UTC, Erwan-loot approved these changes

2023-06-01 13:16 UTC, Erwan-loot requested changes
It should be pointed out that you need to ask support if customers want ip authorization. 
It would be necessary to delete the mentions of the codes with the if

2023-06-01 13:17 UTC, Erwan-loot commented on install_pim/manual/security_recommendations.rst
> +		{% endif %}
```suggestion
	<Location /adminer.php>

		Require all denied
	</Location>

	<Location /app_dev.php>

```

2023-06-01 13:21 UTC, Erwan-loot requested changes

2023-06-01 13:21 UTC, Erwan-loot commented on install_pim/manual/security_recommendations.rst
> +	</Location>
```suggestion
	<Location /adminer.php>
		Require all denied
	</Location>

	<Location /app_dev.php>
		Require all denied
	</Location>
```

2023-06-01 13:21 UTC, Erwan-loot commented on install_pim/manual/security_recommendations.rst
> +On test/dev/staging/pre-prod environments, if needed only, make sure to enable these with IP filtering like the following configuration
```suggestion
On test/dev/staging/pre-prod environments, if needed only, make sure to ask support team to add with authorized IPs
```

2023-06-01 14:54 UTC, Erwan-loot approved these changes

2023-06-02 08:51 UTC, AdeOlubi approved these changes

2023-06-02 08:52 UTC, niarcotyk approved these changes

2023-06-02 08:54 UTC, Airmanbzh approved these changes

2023-06-06 16:03 UTC, merged